---
- name: stop unicorn
  shell:
    bin/unicorn stop
    chdir={{ dest }}
  ignore_errors: yes

- name: start unicorn
  shell:
    bin/unicorn start
    chdir={{ dest }}

- name: restart nginx
  service:
    name=nginx
    enabled=yes
    state=restarted
