---
- name: stop rails
  service:
    name={{ project }}
    state=stopped
  sudo: yes
  ignore_errors: yes

- name: start rails
  service:
    name={{ project }}
    state=started
  sudo: yes

- name: restart nginx
  service:
    name=nginx
    enabled=yes
    state=restarted
  sudo: yes
