---
- name: notify to typetalk
  typetalk:
    client_id={{ typetalk_client_id }}
    client_secret={{ typetalk_client_secret }}
    topic={{ typetalk_topic }}
    msg='{{ colon }}wink{{ colon }} {{ ansible_hostname }} に {{ project }} がデプロイされたよ!'
  when: typetalk_notify
