---
- name: notify to typetalk
  typetalk:
    client_id={{ typetalk_client_id }}
    client_secret={{ typetalk_client_secret }}
    topic={{ typetalk_topic }}
    msg=':wink: {{ ansible_hostname }} に {{ project }} がデプロイされたよ!'
